Hide user settings in Demo Mode
elementary/wingpanel-indicator-session pull request #172
Opened 2022-12-30 08:50 UTC by meisenzahl

Closes https://github.com/elementary/wingpanel-indicator-session/issues/63

### Before

![](https://user-images.githubusercontent.com/10796736/210051930-ebe0d68e-4912-4a93-a127-ec73ce1ffb0f.png)

### After

![](https://user-images.githubusercontent.com/10796736/210051936-4bc94326-fc1c-4aa8-b013-07864539f594.png)

2023-01-01 02:00 UTC, zeebok commented
Is this still an issue with eOS7? I am fairly sure in the early access build that you create a user when you live boot so this wouldn't be needed anymore. But maybe that is changing for release? Hmm I guess that is a question for @danirabbit to answer. If this is something that will be an issue in the future this is definitely a good patch!

2023-01-01 09:20 UTC, meisenzahl commented
I tested this with a daily build ISO of OS 7. Screenshots are taken in Demo Mode.

2023-01-02 17:45 UTC, danirabbit requested changes

2023-01-02 17:45 UTC, danirabbit commented on src/Utils.vala
> +        var proc_cmdline = File.new_for_path ("/proc/cmdline");
Since this is only used in `indicator.vala`, maybe a private method there instead of creating a new utility class?

2023-01-02 18:44 UTC, danirabbit approved these changes
Nice work! :rocket:

2023-01-02 18:44 UTC, merged